version: "3.1"

services:
  app_client:
    build: .
    volumes:
      - .:/go/src/
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysql_client
      MYSQL_PORT: 3306
      MYSQL_CLIENT_DATABASE: keel_client
      MYSQL_INVOICE_DATABASE: keel_invoice
      KEEL_PER_PAGE: 10
      KEEL_LOG_PATH: .
    ports:
      - "8081:8081"
    
  mysql_client:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keel_client
    volumes:
      - ./.mysql:/var/lib/mysql
    ports:
      - "3310:3306"
