version: "3.1"

services:    
  app_invoice:
    build: .
    volumes:
      - .:/go/src/
    environment:
      MYSQL_INVOICE_USER: root
      MYSQL_INVOICE_PASSWORD: root
      MYSQL_INVOICE_HOST: mysql_invoice
      MYSQL_INVOICE_PORT: 3306
      MYSQL_INVOICE_DATABASE: keel_invoice
      KEEL_INVOICE_PER_PAGE: 10
      KEEL_INVOICE_LOG_PATH: .
      KEEL_INVOICE_CLIENT_URL: http://app_client:8081/client/get
    ports:
      - "8082:8081"
    networks:
      - docker_keel

  mysql_invoice:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keel_invoice
    volumes:
      - ./.mysql:/var/lib/mysql
    ports:
      - "3311:3306"
    networks:
      - docker_keel

networks:
  docker_keel:
    driver: bridge