version: "3"

services:
  app:
    build: .
    volumes:
      - .:/go/src/
    ports:
      - "8081:8081"

  db_client:
    image: mysql:5.7
    restart: always
    volumes:
      - .data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=keel_client
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - "3310:3306"
