version: "3.1"

services:
  app:
    build: .
    volumes:
      - .:/go/src/
    ports:
      - "8081:8081"

  db_client:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keel_client
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    ports:
      - "3310:3306"
